[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.1.1",
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.118.0",
    "google-genai>=1.41.0",
    "pydantic-ai[examples]>=1.0.14",
]
